fix zero laste error
gregberge/content-range pull request #5
Opened 2020-11-03 11:14 UTC by L-Luciano

2020-11-04 18:32 UTC, gregberge requested changes

2020-11-04 18:32 UTC, gregberge commented on index.js
> +    var last = options.last ?? (options.first + options.limit - 1);
This syntax is ES2020, could you please do a fix in ES5 like all the code in this repo? Thanks!

2020-11-07 22:38 UTC, L-Luciano commented
Sorry for the delay.

It's done

2020-11-08 21:27 UTC, gregberge approved these changes

2020-11-08 21:28 UTC, merged